import { prisma } from "@/lib/prisma";

function getISOWeekNumber(date: Date): number {
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
  const dayNum = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  return Math.ceil((((d.getTime() - yearStart.getTime()) / 86400000) + 1) / 7);
}

function getNextMonday(from: Date): Date {
  const d = new Date(from);
  const day = d.getDay();
  const daysUntilMonday = day === 0 ? 1 : (8 - day);
  d.setDate(d.getDate() + daysUntilMonday);
  d.setHours(0, 0, 0, 0);
  return d;
}

function addDays(date: Date, days: number): Date {
  const d = new Date(date);
  d.setDate(d.getDate() + days);
  return d;
}

export async function generateWeeklyBatches(weeksAhead: number = 8): Promise<{ created: number; skipped: number }> {
  let created = 0;
  let skipped = 0;

  const courses = ["PROFESSIONAL_MODULE", "AI_MODULE"] as const;
  const coursePrefix: Record<string, string> = {
    PROFESSIONAL_MODULE: "UK-PROF",
    AI_MODULE: "UK-AI",
  };

  let monday = getNextMonday(new Date());

  for (let w = 0; w < weeksAhead; w++) {
    const weekNum = getISOWeekNumber(monday);
    const year = monday.getFullYear();
    const friday = addDays(monday, 4);

    for (const course of courses) {
      const batchName = `${coursePrefix[course]}-W${String(weekNum).padStart(2, "0")}-${year}`;

      // Check if batch already exists for this week/course
      const existing = await prisma.batch.findFirst({
        where: {
          course,
          startDate: { gte: monday, lt: addDays(monday, 1) },
        },
      });

      if (existing) {
        skipped++;
        continue;
      }

      await prisma.batch.create({
        data: {
          name: batchName,
          course,
          startDate: monday,
          endDate: friday,
          capacity: 6,
          status: "UPCOMING",
          location: "Milton Keynes",
          isAutoGenerated: true,
        },
      });
      created++;
    }

    monday = addDays(monday, 7);
  }

  return { created, skipped };
}
