/**
 * Comprehensive import from PLC Training Enquiries.xlsx
 * Creates employees, students, leads, batches from the manual database
 * Usage: npx tsx scripts/import-excel-data.ts
 */

import { PrismaClient } from "@prisma/client";
import * as XLSX from "xlsx";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();
const FILE = "/Users/brijinchacko/Downloads/PLC Training Enquiries.xlsx";

// ===================== HELPERS =====================

function normalizeEmail(e: string | null | undefined): string {
  return (e || "").toString().trim().toLowerCase();
}

function normalizePhone(p: string | number | null | undefined): string {
  return (p || "").toString().replace(/[\s\-\(\)]/g, "").trim();
}

function parseBatchDate(val: any): Date | null {
  if (!val) return null;

  // Excel serial number
  if (typeof val === "number" && val > 40000 && val < 50000) {
    return new Date((val - 25569) * 86400 * 1000);
  }

  // ISO date string
  if (typeof val === "string" && /^\d{4}-\d{2}-\d{2}/.test(val)) {
    return new Date(val);
  }

  // US format: 11/16/2024
  if (typeof val === "string" && /^\d{1,2}\/\d{1,2}\/\d{4}/.test(val)) {
    const [m, d, y] = val.split("/");
    return new Date(parseInt(y), parseInt(m) - 1, parseInt(d));
  }

  // UK format: "10th Mar 2025", "02nd Mar 2026", "9/16/2024"
  if (typeof val === "string") {
    const cleaned = val.replace(/(\d+)(st|nd|rd|th)\s/i, "$1 ");
    const d = new Date(cleaned);
    if (!isNaN(d.getTime())) return d;
  }

  return null;
}

function generateBatchName(date: Date): string {
  const year = date.getFullYear();
  const weekNum = Math.ceil(
    ((date.getTime() - new Date(year, 0, 1).getTime()) / 86400000 + 1) / 7
  );
  return `UK-PROF-W${weekNum}-${year}`;
}

// ===================== STEP 1: CREATE EMPLOYEES =====================

async function createEmployees() {
  console.log("\n========== STEP 1: CREATE EMPLOYEES ==========");

  const employees = [
    { name: "Vaisakh Sankar", email: "vaisakh@wartens.com", role: "ADMIN", dept: "Administration" },
    { name: "Nikhil", email: "nikhil@wartens.com", role: "SALES_LEAD", dept: "Sales" },
    { name: "Yasmeen Banu", email: "yasmeen@wartens.com", role: "ADMISSION_COUNSELLOR", dept: "Admissions" },
    { name: "Araina Asif", email: "araina@wartens.com", role: "ADMISSION_COUNSELLOR", dept: "Admissions" },
    { name: "Sagar", email: "sagar@wartens.com", role: "ADMISSION_COUNSELLOR", dept: "Admissions" },
    { name: "Anisha George", email: "anisha@wartens.com", role: "ADMIN", dept: "Administration" },
  ];

  const defaultPassword = await bcrypt.hash("Wartens@2026!", 12);
  let created = 0;
  let skipped = 0;

  for (const emp of employees) {
    const existing = await prisma.user.findUnique({ where: { email: emp.email } });
    if (existing) {
      console.log(`  ✓ ${emp.name} (${emp.email}) — already exists`);
      skipped++;
      continue;
    }

    const user = await prisma.user.create({
      data: {
        name: emp.name,
        email: emp.email,
        password: defaultPassword,
        role: emp.role as any,
        isActive: true,
        onboarded: true,
      },
    });

    await prisma.employee.create({
      data: {
        userId: user.id,
        department: emp.dept,
        hireDate: new Date(),
      },
    });

    console.log(`  ✓ Created ${emp.name} (${emp.email}) as ${emp.role}`);
    created++;
  }

  console.log(`  Employees: ${created} created, ${skipped} already existed`);
  return { created, skipped };
}

// ===================== STEP 2: CREATE HISTORICAL BATCHES =====================

async function createHistoricalBatches(data: any[]) {
  console.log("\n========== STEP 2: CREATE HISTORICAL BATCHES ==========");

  const batchDates = new Map<string, Date>();

  for (const row of data) {
    const date = parseBatchDate(row.Batch);
    if (!date || isNaN(date.getTime())) continue;
    const name = generateBatchName(date);
    if (!batchDates.has(name)) {
      batchDates.set(name, date);
    }
  }

  let created = 0;
  let skipped = 0;

  for (const [name, startDate] of batchDates) {
    const existing = await prisma.batch.findFirst({ where: { name } });
    if (existing) {
      skipped++;
      continue;
    }

    const endDate = new Date(startDate);
    endDate.setDate(endDate.getDate() + 5); // 5-day course

    const isCompleted = startDate < new Date();

    await prisma.batch.create({
      data: {
        name,
        course: "PROFESSIONAL_MODULE",
        startDate,
        endDate,
        capacity: 6,
        status: isCompleted ? "COMPLETED" : "UPCOMING",
        location: "Milton Keynes",
        isAutoGenerated: false,
      },
    });
    created++;
  }

  console.log(`  Batches: ${created} created, ${skipped} already existed`);
  return { created, skipped };
}

// ===================== STEP 3: IMPORT CERTIFIED STUDENTS =====================

async function importStudents(data: any[]) {
  console.log("\n========== STEP 3: IMPORT CERTIFIED STUDENTS ==========");

  const defaultPassword = await bcrypt.hash("Student@2026!", 12);
  let created = 0;
  let skipped = 0;
  let errors = 0;

  // Get counsellor map
  const counsellors = await prisma.employee.findMany({
    include: { user: { select: { name: true, id: true } } },
  });
  const counsellorMap = new Map<string, string>();
  for (const c of counsellors) {
    const firstName = c.user.name.split(" ")[0].toLowerCase();
    counsellorMap.set(firstName, c.id);
  }

  for (const row of data) {
    try {
      const name = (row["Full Name"] || "").toString().trim();
      const email = normalizeEmail(row["Email ID"]);
      const phone = normalizePhone(row["Mobile Number"]);

      if (!name || !email) { skipped++; continue; }

      // Check if user already exists
      const existing = await prisma.user.findUnique({ where: { email } });
      if (existing) { skipped++; continue; }

      // Parse batch date
      const batchDate = parseBatchDate(row.Batch);
      let batchId: string | null = null;
      if (batchDate && !isNaN(batchDate.getTime())) {
        const batchName = generateBatchName(batchDate);
        const batch = await prisma.batch.findFirst({ where: { name: batchName } });
        batchId = batch?.id || null;
      }

      // Determine status
      const courseStatus = (row["Course status"] || "").toString().toLowerCase();
      let studentStatus: string;
      if (courseStatus === "completed") studentStatus = "COMPLETED";
      else if (courseStatus === "intraining" || courseStatus === "intraning") studentStatus = "ACTIVE";
      else if (row.Placed === "Yes") studentStatus = "ALUMNI";
      else studentStatus = "ACTIVE";

      // Map counsellor
      const counsellorName = (row.Counsellor || "").toString().toLowerCase().trim();
      const counsellorId = counsellorMap.get(counsellorName) || null;

      // Create user
      const user = await prisma.user.create({
        data: {
          name,
          email,
          phone: phone || null,
          password: defaultPassword,
          role: "STUDENT",
          isActive: true,
          onboarded: true,
        },
      });

      // Create student
      await prisma.student.create({
        data: {
          userId: user.id,
          batchId,
          course: "PROFESSIONAL_MODULE",
          status: studentStatus as any,
          currentPhase: courseStatus === "completed" ? 5 : 0,
          paymentStatus: "PAID",
          counsellorId,
          enrollmentDate: batchDate || new Date(),
        },
      });

      created++;
      if (created % 20 === 0) console.log(`  ... ${created} students created`);
    } catch (err: any) {
      errors++;
    }
  }

  console.log(`  Students: ${created} created, ${skipped} skipped, ${errors} errors`);
  return { created, skipped, errors };
}

// ===================== STEP 4: IMPORT RFQ LEADS =====================

async function importRFQLeads(data: any[]) {
  console.log("\n========== STEP 4: IMPORT RFQ LEADS ==========");

  // Build email index for dedup
  const existingEmails = new Set(
    (await prisma.lead.findMany({ select: { email: true } })).map((l) => l.email.toLowerCase())
  );
  const existingStudentEmails = new Set(
    (await prisma.user.findMany({ where: { role: "STUDENT" }, select: { email: true } })).map((u) => u.email.toLowerCase())
  );

  let created = 0;
  let skipped = 0;

  for (const row of data) {
    try {
      const name = (row["Full Name"] || "").toString().trim();
      const email = normalizeEmail(row["Email ID"]);
      const phone = normalizePhone(row["Mobile Number"]);
      const comments = (row.Comments || "").toString().trim();
      const source = (row.Source || "website").toString().trim();
      const counsellor = (row.counsellor || "").toString().trim();

      if (!name || !email) { skipped++; continue; }
      if (existingEmails.has(email) || existingStudentEmails.has(email)) { skipped++; continue; }

      await prisma.lead.create({
        data: {
          name,
          email,
          phone: phone || "",
          courseInterest: "PROFESSIONAL_MODULE",
          source: source || "Excel Import",
          status: comments?.toLowerCase().includes("enrolled") ? "ENROLLED" : "NEW",
        },
      });

      // Add notes if comments exist
      if (comments) {
        const lead = await prisma.lead.findFirst({ where: { email } });
        if (lead) {
          await prisma.leadNote.create({
            data: {
              leadId: lead.id,
              content: `[Excel Import] Counsellor: ${counsellor || "N/A"} | ${comments}`,
              createdBy: "Excel Import",
            },
          });
        }
      }

      existingEmails.add(email);
      created++;
      if (created % 100 === 0) console.log(`  ... ${created} leads imported`);
    } catch {
      skipped++;
    }
  }

  console.log(`  RFQ Leads: ${created} created, ${skipped} skipped`);
  return { created, skipped };
}

// ===================== STEP 5: IMPORT QUALITY + 2025 LEADS =====================

async function importDetailedLeads(data: any[], sheetName: string) {
  console.log(`\n========== STEP 5: IMPORT ${sheetName.toUpperCase()} ==========`);

  const existingEmails = new Set(
    (await prisma.lead.findMany({ select: { email: true } })).map((l) => l.email.toLowerCase())
  );

  let created = 0;
  let skipped = 0;
  let notesAdded = 0;

  for (const row of data) {
    try {
      const name = (row["Full Name"] || "").toString().trim();
      const email = normalizeEmail(row["Email ID"]);
      const phone = normalizePhone(row["Mobile No."] || row["Mobile Number"]);
      const counsellor = (row.Counselor || row.Counsellor || "").toString().trim();
      const visa = (row["Visa Status"] || "").toString().trim();
      const education = (row.Education || "").toString().trim();
      const experience = (row.Experience || "").toString().trim();
      const comment = (row.Comment || "").toString().trim();
      const interested = (row["Interested "] || row.Interested || "").toString().trim();
      const enrolled = (row.Enrolled || "").toString().trim();
      const usp = (row.USP || "").toString().trim();

      if (!name || !email) { skipped++; continue; }

      if (existingEmails.has(email)) {
        // Add notes to existing lead
        const existingLead = await prisma.lead.findFirst({ where: { email } });
        if (existingLead && comment) {
          await prisma.leadNote.create({
            data: {
              leadId: existingLead.id,
              content: `[${sheetName}] Counsellor: ${counsellor} | Visa: ${visa} | Education: ${education} | Experience: ${experience} | ${comment}`,
              createdBy: "Excel Import",
            },
          });
          notesAdded++;
        }
        skipped++;
        continue;
      }

      // Determine status
      let status = "NEW";
      if (enrolled?.toLowerCase() === "yes") status = "ENROLLED";
      else if (interested?.toLowerCase() === "yes") status = "QUALIFIED";
      else if (comment) status = "CONTACTED";

      await prisma.lead.create({
        data: {
          name,
          email,
          phone: phone || "",
          courseInterest: "PROFESSIONAL_MODULE",
          qualification: education || null,
          source: `Excel - ${sheetName}`,
          status: status as any,
        },
      });

      // Add detailed note
      const lead = await prisma.lead.findFirst({ where: { email } });
      if (lead) {
        const noteContent = [
          counsellor ? `Counsellor: ${counsellor}` : "",
          visa ? `Visa: ${visa}` : "",
          education ? `Education: ${education}` : "",
          experience ? `Experience: ${experience}` : "",
          usp ? `USP: ${usp}` : "",
          comment ? `Notes: ${comment}` : "",
        ].filter(Boolean).join(" | ");

        if (noteContent) {
          await prisma.leadNote.create({
            data: {
              leadId: lead.id,
              content: `[${sheetName}] ${noteContent}`,
              createdBy: "Excel Import",
            },
          });
          notesAdded++;
        }
      }

      existingEmails.add(email);
      created++;
    } catch {
      skipped++;
    }
  }

  console.log(`  ${sheetName}: ${created} created, ${skipped} skipped, ${notesAdded} notes added`);
  return { created, skipped, notesAdded };
}

// ===================== STEP 6: IMPORT OFFLINE STUDENTS =====================

async function importOfflineStudents(data: any[]) {
  console.log("\n========== STEP 6: IMPORT OFFLINE STUDENTS ==========");

  const defaultPassword = await bcrypt.hash("Student@2026!", 12);
  const existingEmails = new Set(
    (await prisma.user.findMany({ select: { email: true } })).map((u) => u.email.toLowerCase())
  );

  let created = 0;
  let skipped = 0;

  for (const row of data) {
    try {
      const name = (row.Name || "").toString().trim();
      const email = normalizeEmail(row.Email);
      const phone = normalizePhone(row.Mobile);
      const batchStr = (row.Batch || "").toString().trim();

      if (!name || !email) { skipped++; continue; }
      if (existingEmails.has(email)) { skipped++; continue; }

      // Parse batch date
      const batchDate = parseBatchDate(batchStr);
      let batchId: string | null = null;
      if (batchDate && !isNaN(batchDate.getTime())) {
        const batchName = generateBatchName(batchDate);
        const batch = await prisma.batch.findFirst({ where: { name: batchName } });
        batchId = batch?.id || null;
      }

      const user = await prisma.user.create({
        data: {
          name,
          email,
          phone: phone || null,
          password: defaultPassword,
          role: "STUDENT",
          isActive: true,
          onboarded: true,
        },
      });

      await prisma.student.create({
        data: {
          userId: user.id,
          batchId,
          course: "PROFESSIONAL_MODULE",
          status: batchDate && batchDate < new Date() ? "COMPLETED" : "ACTIVE",
          currentPhase: 0,
          paymentStatus: "PAID",
          enrollmentDate: batchDate || new Date(),
        },
      });

      existingEmails.add(email);
      created++;
    } catch {
      skipped++;
    }
  }

  console.log(`  Offline: ${created} created, ${skipped} skipped`);
  return { created, skipped };
}

// ===================== MAIN =====================

async function main() {
  console.log("====================================================");
  console.log("  COMPREHENSIVE DATA IMPORT FROM EXCEL");
  console.log("  File:", FILE);
  console.log("====================================================");

  const wb = XLSX.readFile(FILE);

  // Step 1: Create employees
  const empResult = await createEmployees();

  // Step 2: Create historical batches from certified professionals
  const certData = XLSX.utils.sheet_to_json(wb.Sheets["Wartens Certified Professionals"]);
  const offlineData = XLSX.utils.sheet_to_json(wb.Sheets["Offline "]);
  const allBatchData = [...certData, ...offlineData];
  const batchResult = await createHistoricalBatches(allBatchData);

  // Step 3: Import certified students
  const studentResult = await importStudents(certData);

  // Step 4: Import RFQ leads
  const rfqData = XLSX.utils.sheet_to_json(wb.Sheets["RFQ"]);
  const rfqResult = await importRFQLeads(rfqData);

  // Step 5: Import quality leads and 2025 completed calls
  const qualData = XLSX.utils.sheet_to_json(wb.Sheets["Quality leads"]);
  const qualResult = await importDetailedLeads(qualData, "Quality Leads");

  const calls25Data = XLSX.utils.sheet_to_json(wb.Sheets["2025 Completed calls"]);
  const calls25Result = await importDetailedLeads(calls25Data, "2025 Completed Calls");

  // Step 6: Import offline students
  const offResult = await importOfflineStudents(offlineData);

  // Summary
  console.log("\n====================================================");
  console.log("  IMPORT COMPLETE - SUMMARY");
  console.log("====================================================");
  console.log(`  Employees: ${empResult.created} created`);
  console.log(`  Batches: ${batchResult.created} created`);
  console.log(`  Students (Certified): ${studentResult.created} created`);
  console.log(`  Students (Offline): ${offResult.created} created`);
  console.log(`  Leads (RFQ): ${rfqResult.created} created`);
  console.log(`  Leads (Quality): ${qualResult.created} created`);
  console.log(`  Leads (2025 Calls): ${calls25Result.created} created`);

  // Final counts
  const totalUsers = await prisma.user.count();
  const totalStudents = await prisma.student.count();
  const totalLeads = await prisma.lead.count();
  const totalBatches = await prisma.batch.count();
  const totalEmployees = await prisma.employee.count();
  console.log(`\n  Database totals:`);
  console.log(`    Users: ${totalUsers}`);
  console.log(`    Students: ${totalStudents}`);
  console.log(`    Leads: ${totalLeads}`);
  console.log(`    Batches: ${totalBatches}`);
  console.log(`    Employees: ${totalEmployees}`);

  await prisma.$disconnect();
}

main().catch((err) => {
  console.error("Import failed:", err);
  prisma.$disconnect();
  process.exit(1);
});
